baseURL = 'http://127.0.0.1:1313'
publishDir = "public/local"

languageCode = 'en'
title = 'Chase Your Dreams'
copyright = "Copyright © 2012–2026, Yogendra Rampuria; all rights reserved."
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

disqusShortname = "yogendrarampuria"
theme = "hugo-clarity"

# Google analytics
googleAnalytics = "UA-21164716-2"

# Pagination
[pagination]
  pagerSize = 10
  path = "page"

# [languages]
# config/_default/languages.toml

# [menus]
#   config/_default/menus/menu.xx.toml

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[outputs]
home = ["HTML", "RSS", "JSON"]