enableSearch = true
customCSS = ["css/custom.css", "css/events.css"]
customJS = ["js/custom.js"]

twitter = "@yogendra"
largeTwitterCard = true 
introDescription = "Software Engineer | OSS Advocate, User, Buyer and Seller"
introURL = "about/" 
description = "Chase Your Dream"

showShare = true

ga_analytics = "UA-21164716-2"

numberOfTagsShown = 14 
usePageBundles = true
fallBackOgImage = "images/thumbnail.png"
codeMaxLines = 10
codeLineNumbers = true
enableMathNotation = false
mainSections = ["posts"] 
centerLogo = false 
logo = "images/logo-64.png"
figurePositionShow = true 
figurePositionLabel = "Figure" 
mobileNavigation = "left" 
enforceLightMode = false

languageMenuName = "🌐"



numberOfRecentPosts = 8

numberOfFeaturedPosts = 8

since = 2012

iconsDir = "icons/" 
showRelatedInArticle = true

[author]
    name = "Yogi"
    photo = "images/authors/yogi.jpg" #include this if you would like to show the author photo on the sidebar

[version]
    tag = "v00000000.1"