#!/usr/bin/env bash

set -Eeuo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT_NAME=$( basename ${BASH_SOURCE[0]} )
PROJECT_DIR=$( cd $SCRIPT_DIR/..; pwd)
SCRIPT=$SCRIPT_DIR/$SCRIPT_NAME


function help(){

  cat <<EOF
SUB-COMMANDS
$(cat ${SCRIPT} | grep '^function'| sed -E 's/function (.+)\(\){/\1/')
EOF
}

function deploy(){
  build
  publish
}
function build(){
  hugo --minify --cleanDestinationDir -e firebase
  hugo --minify --cleanDestinationDir -e github
}
function publish(){
  export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gac.json
  echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" >> $GOOGLE_APPLICATION_CREDENTIALS
  firebase deploy --only hosting
}

function build-beta(){
  hugo --minify --cleanDestinationDir -e firebase-beta
}
function publish-beta(){
  export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gac.json
  echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" >> $GOOGLE_APPLICATION_CREDENTIALS
  firebase deploy --only hosting:yogendra-me-beta
}

function deploy-beta(){
  build-beta
  publish-beta
}

function build-local(){
  hugo --minify --cleanDestinationDir -e local
}
function start-local(){
  killall hugo &>> /dev/null || true
  nohup hugo  --gc --enableGitInfo -DFE  --cleanDestinationDir -e local serve &> hugo.log &
}

function devcontainer-build(){
  SCOPE_DIR=${PROJECT_DIR}/.devcontainer
  DOCKERFILE=${SCOPE_DIR}/Dockerfile
  IMAGE_NAME=ghcr.io/yogendra/yogendra-me-devcontainer
  docker buildx build -t ${IMAGE_NAME}:latest --platform=linux/amd64 --platform=linux/arm64 --push -f ${DOCKERFILE} ${SCOPE_DIR}
}

OP=${1:-help}; shift
$OP $@
