#!/usr/bin/env bash

OP=$1; shift

PLATUML_JAR=${PLANTUML_JAR:=lib/platuml.jar}
function prepare_plantuml(){
  find ./content -type f \( -iname '*.puml' -o -iname '*.plantuml' \) | while read puml
  do
    filename=$(basename $puml)
    dest=${filename%.*}
    echo java -jar $PLANTUML_JAR -tpng -tsvg -o $dest  $puml
  done
}

function prepare(){
  prepare_plantuml
}
function deploy(){
  build
  publish
}
function build(){
  prepare
  hugo --minify --cleanDestinationDir -e firebase
  hugo --minify --cleanDestinationDir -e github
}
function publish(){
  firebase deploy --only hosting
}

function build-beta(){
  prepare
  hugo --minify --cleanDestinationDir -e firebase-beta
}
function publish-beta(){
  firebase deploy --only hosting:yogendra-me-beta
}

function deploy-beta(){
  build-beta
  publish-beta
}
$OP $@
