#!/usr/bin/env bash

set -Eeuo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR=$( cd $SCRIPT_DIR/..; pwd)


OP=$1; shift

PLATUML_JAR=${PLANTUML_JAR:=${PROJECT_DIR}/lib/platuml.jar}
function prepare_plantuml(){
  find $PROJECT_DIR/content -type f \( -iname '*.puml' -o -iname '*.plantuml' \) | while read puml
  do
    filename=$(basename $puml)
    dest=${filename%.*}
    echo java -jar $PLANTUML_JAR -tpng -tsvg -o $dest  $puml
  done
}

function prepare(){
  prepare_plantuml
}
function deploy(){
  build
  publish
}
function build(){
  prepare
  hugo --minify --cleanDestinationDir -e firebase
  hugo --minify --cleanDestinationDir -e github
}
function publish(){
  firebase deploy --only hosting
}

function build-beta(){
  prepare
  hugo --minify --cleanDestinationDir -e firebase-beta
}
function publish-beta(){
  firebase deploy --only hosting:yogendra-me-beta
}

function deploy-beta(){
  build-beta
  publish-beta
}

function build-local(){
  prepare
  hugo --minify --cleanDestinationDir -e local
}
function start-local(){
  killall hugo &>> /dev/null || true
  nohup hugo  --gc --enableGitInfo -DFE  --cleanDestinationDir -e local serve &> hugo.log &
}

function devcontainer-build(){
  SCOPE_DIR=${PROJECT_DIR}/.devcontainer
  DOCKERFILE=${SCOPE_DIR}/Dockerfile
  IMAGE_NAME=ghcr.io/yogendra/yogendra-me-devcontainer
  docker buildx build -t ${IMAGE_NAME}:latest --platform=linux/amd64 --platform=linux/arm64 --push -f ${DOCKERFILE} ${SCOPE_DIR}
}

$OP $@
