#!/usr/bin/env bash
PLATUML_JAR_LOCATION=http://sourceforge.net/projects/plantuml/files/plantuml.jar/download

platform="darwin"
arch="x64"

function install_plantuml(){
  if [ ! -f lib/plantuml.jar ]; then
    mkdir -p lib/
    curl -L $PLATUML_JAR_LOCATION -o lib/plantuml.jar
  fi
  install_graphviz_${platform}
}

function install_firebase(){
  curl -sL firebase.tools | bash
}

function brew_install() {
    if ! brew list $1 &>/dev/null; then
      echo "\nInstalling $1"
      brew install $1
    fi
    brew link -f --overwrite $1
}

function install_hugo_darwin(){
  brew_install hugo asciidoctor
}

function install_hugo_linux(){
  sudo apt update
  sudo apt install hugo asciidoctor
}
function install_graphviz_darwin(){
  brew_install libtool
  brew_install graphviz
}
function install_jre_darwin(){
  brew_install temurin-17
}
function instll_jre_linux(){
  sudo apt update
  sudo apt install adoptopenjdk-11-hotspot
}
function install_graphviz_linux(){
  sudo apt install graphviz
}
function init(){
  install_hugo_${platform}
  install_firebase
  install_plantuml
  install_jre_${platform}
}

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  platform="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  platform="darwin"
else
  platform="unsupported"
fi
init


