name: 🧪 Deploy to Beta Testing
on:
  push:
    branches:
      - main
    paths:
      - "!.devcontainer/**"
      - "!.github/workflows/publish-devcontainer.yml"
      - "**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: 🔨 Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: ⬇️ Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: 📦 Install go-task
        id: install
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: 🎬 Initialize Environment
        id: init
        run: task init

      - name: 🐍 Setup Conda
        id: setup_conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: yogendra-me
          environment-file: environment.yml
          auto-activate-base: false
      
      - name: 🚀 Build and Deploy to Beta
        id: build_and_deploy
        run: | 
          task version VERSION="${{ github.sha }}"
          task beta:deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_YOGENDRA_ME }}

      - name: 📊 Get Build Info
        id: build_info
        run: |
          echo "build_info<<EOF" >> $GITHUB_OUTPUT
          task build-info >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: 🏷️ Get Production Version
        id: prod_version
        run: |          
          echo "prod_version=$(task prod_version)" >> $GITHUB_OUTPUT

      - name: 🪵 Generate Changelog
        id: changelog
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          task changelog >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 📁 Get Changed Files
        id: files
        run: |         
          echo "files<<EOF" >> $GITHUB_OUTPUT
          task changes >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 🎯 Next Release Version
        id: next_version
        run: |
          echo "next_version=$(task next_version)" >> $GITHUB_OUTPUT

      - name: 🎟️ Create Testing Ticket
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/BETA_TESTING.md
          update_existing: true
          search_existing: open
        env:          
          NEXT_VERSION: ${{ steps.next_version.outputs.next_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYED_AT: "${{ github.event.head_commit.timestamp || 'Now' }}"
          COMMIT_SHA: "${{ github.sha }}"
          PRODUCTION_VERSION: "${{ steps.prod_version.outputs.prod_version }}"
          AUTHOR: "${{ github.event.head_commit.author.name }}"
          BUILD_INFO: ${{ steps.build_info.outputs.build_info }}
          ACTION_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          DIFF_URL: "https://github.com/${{ github.repository }}/compare/${{ steps.prod_version.outputs.prod_version }}...${{ github.sha }}"
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          CHANGED_FILES: ${{ steps.files.outputs.files }}
      - name: 📢 Generate Summary
        id: summary
        run: |
          echo ## 🚀 Beta Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "[Beta Testing Ticket #${{steps.create-issue.outputs.number}}](${{steps.create-issue.outputs.url}})" >> $GITHUB_STEP_SUMMARY
