# .github/workflows/main.yml
on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: CI/CD Automation
    steps:
      - uses: actions/checkout@v2
      - name: Automation step 1
        uses: ./.github/actions/devcontainer-action

